[tool.poetry]

name = "elections"
version = "1.0.0"
description = "Voter registration status and ballots for Michigan."

authors = ["Jace Browning <jacebrowning@gmail.com>"]

[tool.poetry.dependencies]

python = "^3.7"

# Django
django = "^2.1"
django-grappelli = "^2.11"
django-filter = "^2.0"
django-model-utils = "^3.1"

# Django REST Framework
djangorestframework = "^3.8"
drf-yasg = "^1.9"
django-cors-headers = "^2.4"

# Databases
dj-database-url = "^0.5.0"
psycopg2-binary = "*"

# Caches
django-redis-cache = "*"

# Markdown
markdown = "*"
pymdown-extensions = "*"
pygments = "*"

# Utilities
minilog = "^1.2.3"
factory_boy = "*"
pendulum = "*"
requests_cache = "*"
beautifulsoup4 = "^4.6"
fake-useragent = "~0.1.11"
requests = "^2.19"

# Production Server
gunicorn = "^19.8"
whitenoise = "^3.3"
bugsnag = "^3.4"

[tool.poetry.dev-dependencies]

# Formatting
isort = "4.3.4"
black = "18.9b0"

# Linters
pylint = "^2.0"
pylint-django = "*"
mypy = "*"

# Testing
pytest = "^3.6"
pytest-django = "*"
pytest-describe = "*"
pytest-expecter = "^1.3"
pytest-vcr = "*"
pytest-cov = "*"
pytest-watch = "*"

# Utilities
django-extensions = "*"
pygraphviz = "*"

# Development Server
django-debug-toolbar = "*"
django-livereload-server = "*"
